# Generated by Django 5.1.7 on 2025-05-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='enemy_hits',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='enemy_misses',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='player_hits',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='player_misses',
            field=models.JSONField(default=list),
        ),
    ]
